"""
Agent Code Generator.

Generates code artifacts (files) from requirement + plan.
"""

from __future__ import annotations

import json
import logging
from typing import Any, Dict, List, Optional, Tuple

from infrastructure.llm.provider import LLMRequest, LLMRouter


logger = logging.getLogger(__name__)


def deterministic_codegen(requirement: str) -> Tuple[Dict[str, Any], Dict[str, Any]]:
    content = (
        '"""\n'
        "Generated by CognitionOS single-agent runtime.\n\n"
        f"Requirement:\n{requirement}\n"
        '"""\n\n'
        "from __future__ import annotations\n\n"
        "def run() -> str:\n"
        '    \"\"\"Entry point for the generated artifact.\"\"\"\n'
        f"    return {requirement!r}\n"
    )
    return (
        {
            "version": "v1",
            "strategy": "deterministic",
            "files": [
                {
                    "path": "generated_agent_output.py",
                    "language": "python",
                    "content": content,
                }
            ],
            "notes": "Deterministic fallback codegen (no LLM configured).",
        },
        {"tokens": {"total_tokens": 0}, "cost_usd": 0.0, "model": None, "provider": None},
    )


async def llm_codegen(
    requirement: str,
    plan: Dict[str, Any],
    *,
    llm: LLMRouter,
    model: str,
    max_tokens: int = 1800,
) -> Tuple[Dict[str, Any], Dict[str, Any]]:
    system = (
        "You are a senior engineer. Output ONLY valid JSON. "
        "Schema: {\"version\":\"v1\",\"strategy\":\"llm\",\"files\":[{\"path\":str,"
        "\"language\":\"python\",\"content\":str}],\"notes\":str}. "
        "Constraints: generate self-contained Python 3.11+ code; avoid external dependencies."
    )
    req = LLMRequest(
        messages=[
            {"role": "system", "content": system},
            {"role": "user", "content": json.dumps({"requirement": requirement, "plan": plan})},
        ],
        model=model,
        temperature=0.3,
        max_tokens=max_tokens,
        metadata={"purpose": "agent_codegen"},
    )
    resp = await llm.generate(req)
    usage = {"tokens": resp.usage, "cost_usd": resp.cost_usd, "model": resp.model, "provider": resp.provider.value}
    try:
        data = json.loads(resp.content)
        files = data.get("files", [])
        if not isinstance(files, list) or not files:
            raise ValueError("No files produced")
        for f in files:
            if not isinstance(f, dict) or "path" not in f or "content" not in f:
                raise ValueError("Invalid file entry")
        return data, usage
    except Exception as exc:  # noqa: BLE001
        logger.warning("LLM codegen output invalid JSON; falling back to deterministic", exc_info=True)
        fallback, _ = deterministic_codegen(requirement)
        fallback["llm_raw"] = resp.content
        fallback["llm_error"] = str(exc)
        return fallback, usage

